# The 'type' should be "label" for short meta tags and "text" for ones which
# could get longer, especially ones which use a textarea field instead of a
# textfield.

metatag.metatag_tag.acquia_cards_title:
  type: text
  label: 'Acquia Cards: Title'
metatag.metatag_tag.acquia_cards_desc:
  type: label
  label: "Acquia Cards: Description"
metatag.metatag_tag.acquia_cards_image:
  type: label
  label: 'Acquia Cards: Image'
